---

apiVersion: v1
baseDomain: '%%CLUSTER_DOMAIN%%'
compute:
    - name: worker
      replicas: 0
controlPlane:
    name: master
    replicas: 1
metadata:
    name: '%%CLUSTER_NAME%%'
networking:
    clusterNetwork:
        - cidr: 10.128.0.0/14
          hostPrefix: 23
    machineNetwork:
        - cidr: "%%CLUSTER_CIDR%%"
    networkType: OVNKubernetes
    serviceNetwork:
        - 172.30.0.0/16
platform:
  none: {}
bootstrapInPlace:
  installationDisk: '%%CLUSTER_INSTALL_DISK%%'
pullSecret: '%%CLUSTER_PULL_SECRET%%'
sshKey: '%%CLUSTER_SSH_KEY%%'
